services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: sentrix-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  californium-backend:
    build:
      context: ./californium
    container_name: sentrix-coap-backend

  proxy-core:
    build:
      context: ../proxy-core
    container_name: sentrix-proxy-core
    environment:
      SENTRIX_MQTT_PROXY_PORT: "1884"
      SENTRIX_MQTT_BROKER_HOST: "mosquitto"
      SENTRIX_MQTT_BROKER_PORT: "1883"
      SENTRIX_COAP_PROXY_PORT: "5684"
      SENTRIX_COAP_BACKEND_HOST: "californium-backend"
      SENTRIX_COAP_BACKEND_PORT: "5683"
      SENTRIX_METRICS_PATH: "/shared/metrics.json"
      SENTRIX_EVENTS_PATH: "/shared/events.log"
    ports:
      - "1884:1884"
      - "5684:5684/udp"
    depends_on:
      - mosquitto
      - californium-backend
    volumes:
      - sentrix-metrics:/shared

  metrics-api-stub:
    image: python:3.11-slim
    container_name: sentrix-metrics-api
    command: ["python", "/app/metrics_api_stub.py"]
    environment:
      SENTRIX_METRICS_PATH: "/shared/metrics.json"
      SENTRIX_EVENTS_PATH: "/shared/events.log"
    working_dir: /app
    volumes:
      - ./scripts:/app:ro
      - sentrix-metrics:/shared:ro
    ports:
      - "8080:8080"

volumes:
  sentrix-metrics:
